name: Lint

# Trigger when branches are pushed
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set Python version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Cache dependencies
      - name: Cache dependencies setup
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      # Pylint
      - name: Run pylint
        uses: wearerequired/lint-action@v2
        with:
          pylint: true
          pylint_args: "app.py"